server:
  port: 8280
  servlet.context-path: /order-service

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-uri: http://localhost:8080/authorization-service/oauth/token_key

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: https://idp.example.com
          jwk-set-uri: http://localhost:8000/authorization-service/.well-known/jwks.json

app:
  id: id-123